name: pyart_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - arm_pyart=1.11.6=py38h6c62de6_1
  - brotli=1.0.9=h7f98852_6
  - brotli-bin=1.0.9=h7f98852_6
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2021.10.26=h06a4308_2
  - certifi=2021.10.8=py38h06a4308_2
  - cftime=1.5.2=py38h6c62de6_0
  - click=8.0.3=pyhd3eb1b0_0
  - curl=7.81.0=h494985f_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - dataclasses=0.8=pyh6d0b6a4_7
  - flask=2.0.2=pyhd3eb1b0_0
  - fonttools=4.29.1=py38h497a2fe_0
  - freetype=2.10.4=h0708190_1
  - hdf4=4.2.15=h10796ff_3
  - hdf5=1.12.1=nompi_h7f166f4_103
  - importlib-metadata=4.10.1=py38h578d9bd_0
  - importlib_metadata=4.10.1=hd8ed1ab_0
  - itsdangerous=2.0.1=pyhd3eb1b0_0
  - jbig=2.1=h7f98852_2003
  - jinja2=3.0.2=pyhd3eb1b0_0
  - jpeg=9e=h7f98852_0
  - kiwisolver=1.3.2=py38h1fd1430_1
  - krb5=1.19.2=h48eae69_3
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=3.0=h9c3ff4c_0
  - libblas=3.9.0=13_linux64_openblas
  - libbrotlicommon=1.0.9=h7f98852_6
  - libbrotlidec=1.0.9=h7f98852_6
  - libbrotlienc=1.0.9=h7f98852_6
  - libcblas=3.9.0=13_linux64_openblas
  - libcurl=7.81.0=h494985f_0
  - libdeflate=1.8=h7f98852_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=11.2.0=h1d223b6_12
  - libgfortran-ng=11.2.0=h69a702a_12
  - libgfortran5=11.2.0=h5c6108e_12
  - libgomp=11.2.0=h1d223b6_12
  - liblapack=3.9.0=13_linux64_openblas
  - libnetcdf=4.8.1=nompi_hb3fd0d9_101
  - libnghttp2=1.46.0=ha19adfc_0
  - libnsl=2.0.0=h7f98852_0
  - libopenblas=0.3.18=pthreads_h8fe5266_0
  - libpng=1.6.37=h21135ba_2
  - libssh2=1.10.0=ha35d2d1_2
  - libstdcxx-ng=11.2.0=he4da1e4_12
  - libtiff=4.3.0=h6f004c6_2
  - libwebp-base=1.2.2=h7f98852_1
  - libzip=1.8.0=h1c5bbd1_1
  - libzlib=1.2.11=h36c2ea0_1013
  - lz4-c=1.9.3=h9c3ff4c_1
  - markupsafe=2.0.1=py38h27cfd23_0
  - matplotlib-base=3.5.1=py38hf4fb855_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.3=h9c3ff4c_0
  - netcdf4=1.5.8=nompi_py38h2823cc8_101
  - numpy=1.22.1=py38h6ae9a64_0
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.4.0=hb52868f_1
  - openssl=3.0.0=h7f98852_2
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.4.0=py38h43a58ef_0
  - pillow=8.4.0=py38h8e6f84c_0
  - pip=22.0.2=pyhd8ed1ab_0
  - pyparsing=3.0.7=pyhd8ed1ab_0
  - python=3.8.12=h0744224_3_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytz=2021.3=pyhd8ed1ab_0
  - readline=8.1=h46c0cb4_0
  - scipy=1.7.3=py38h56a6a73_0
  - setuptools=60.6.0=py38h578d9bd_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.37.0=h9cd32fc_0
  - tk=8.6.11=h27826a3_1
  - trmm_rsl=1.49=3
  - typing_extensions=4.0.1=pyha770c72_0
  - unicodedata2=14.0.0=py38h497a2fe_0
  - werkzeug=2.0.2=pyhd3eb1b0_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - xarray=0.21.1=pyhd8ed1ab_0
  - xz=5.2.5=h516909a_1
  - zipp=3.7.0=pyhd8ed1ab_0
  - zlib=1.2.11=h36c2ea0_1013
  - zstd=1.5.2=ha95c52a_0
  - pip:
    - boto3==1.20.46
    - botocore==1.23.46
    - jmespath==0.10.0
    - nexradaws==1.1
    - s3transfer==0.5.0
    - urllib3==1.26.8
prefix: /home/shubham/miniconda3/envs/pyart_env
