apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonservice
spec:
  selector:
    matchLabels:
      run: pythonservice
  replicas: 1
  template:
    metadata:
      labels:
        run: pythonservice
    spec:
      containers:
        hostNetwork: true
        - name: pythonservice
          image: sbmthakur/ingestor
          resources:
            #requests:
            #memory: "700Mi"
            limits:
              memory: "10Gi"
          ports:
            - containerPort: 5000
