# This is a basic workflow to help you get started with Actions

name: ingestor_build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ nasa-ingestor ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: pyart_env
          environment-file: ./ingestor/environment.yml
          python-version: 3.8
          auto-activate-base: false
      - run: |
          cd ingestor
          #pylint server.py
          #pytest
  build:
    runs-on: ubuntu-latest
    #strategy:
    #  fail-fast: false
    #  matrix:
    #    python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v2
    - name: build and push docker image
      id: docker-build
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: sbmthakur/ingestor
        tags: latest,${{ github.sha }}
        registry: docker.io
        directory: ingestor
        dockerfile: ingestor/Dockerfile
        username: sbmthakur
        password: 4ef776e8-82d4-471e-830d-0069bfa99d47
    - name: Print docker image tags
      run: echo "Image tags ${{ steps.docker-build.outputs.tags }}"
